name: "flutter_design_system_mobile_example"
description: A showcase app for the flutter design system mobile from SBB.
version: 2.3.0+20010402 # automatically set by GH Action 
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^10.0.0

  # https://pub.dev/packages/provider
  provider: ^6.0.2

  # https://pub.dev/packages/animations
  animations: ^2.0.3

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.6

  # https://pub.dev/packages/intl
  intl: '>=0.19.0 <0.21.0'

  sbb_design_system_mobile:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.0.0
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
