name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^4.0.1

  # https://pub.dev/packages/provider
  provider: ^6.0.2

  # https://pub.dev/packages/animations
  animations: ^2.0.3

  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.6

  # https://pub.dev/packages/intl
  intl: ^0.17.0

  design_system_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner: ^2.1.10

flutter:
  assets:
   - assets/images/