name: sbb_design_system_mobile
description: The official SBB design system mobile for Flutter.
homepage: https://digital.sbb.ch/de/design-system/mobile/overview/
repository: https://github.com/SchweizerischeBundesbahnen/design_system_flutter
issue_tracker: https://github.com/SchweizerischeBundesbahnen/design_system_flutter/issues
topics: [ icons, theme, design, design-system ]

# set by Github Action
version: 4.0.0 # automatically set by GH Action 

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/intl
  intl: '>=0.19.0 <0.21.0'
  # https://pub.dev/packages/collection
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_lints
  flutter_lints: ^6.0.0

# https://dart.dev/tools/pub/pubspec#platforms
platforms:
  android:
  ios:


flutter:
  assets:
    - lib/fonts/
    - lib/assets/
    - lib/assets/illustrations/dark/
    - lib/assets/illustrations/light/
  fonts:
    - family: SBBWebUltraLight
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-UltraLight.ttf
    - family: SBBWebThin
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Thin.ttf
    - family: SBBWebLight
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Light.ttf
    - family: SBBWebRoman
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Roman.ttf
    - family: SBBWebBold
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Bold.ttf
    - family: SBBWebCondensedBold
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Condensed-Bold.ttf
    - family: SBBWebCondensedHeavy
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/SBBWeb-Condensed-Heavy.ttf
    - family: SBBIconsSmall
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/sbb_icons_small.ttf
    - family: SBBIconsMedium
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/sbb_icons_medium.ttf
    - family: SBBIconsLarge
      fonts:
        - asset: packages/sbb_design_system_mobile/fonts/sbb_icons_large.ttf
